kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5100"]
    endpoint = ["http://host.docker.internal:5100"]
nodes:
  - role: control-plane
  - role: worker
  - role: worker